version: '3.3'

services:
   mysql:
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: Abc123!
       MYSQL_DATABASE: php
       MYSQL_USER: php
       MYSQL_PASSWORD: 4linux

   app:
     depends_on:
     - mysql
     image: php-ms
     ports:
     - "8080:8080"
     environment:
       DB_HOST: mysql
       DB_PORT: 3306
       DB_USER: php
       DB_PASS: 4linux
       DB_NAME: php
